import os
from PIL import Image

def generate_favicons():
    public_dir = "public"
    template_path = r"C:\Users\Farhan\.gemini\antigravity\brain\4792ea95-c894-432e-8d64-7e78bb9b9d70\silicon_epoch_favicon_logo_1781384272505.png"

    if not os.path.exists(public_dir):
        os.makedirs(public_dir)

    # 1. Write the vector favicon.svg
    svg_content = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none">
  <!-- Rounded deep-charcoal badge background -->
  <rect width="32" height="32" rx="10" fill="#1C1B19"/>
  <!-- Sleek, premium glowing orange silicon crystal geometric lattice -->
  <path d="M16 6L24.6603 11V21L16 26L7.33975 21V11L16 6Z" stroke="#D94E1D" stroke-width="1.8" stroke-linejoin="round"/>
  <path d="M16 6V26" stroke="#D94E1D" stroke-width="1.2" opacity="0.6"/>
  <path d="M7.33975 11L24.6603 21" stroke="#D94E1D" stroke-width="1.2" opacity="0.6"/>
  <path d="M7.33975 21L24.6603 11" stroke="#D94E1D" stroke-width="1.2" opacity="0.6"/>
  <circle cx="16" cy="16" r="4.5" fill="#1C1B19" stroke="#FAF9F6" stroke-width="1.5"/>
  <circle cx="16" cy="16" r="1.8" fill="#D94E1D"/>
  <!-- Geodesic nodal points -->
  <circle cx="16" cy="6" r="1.2" fill="#FAF9F6"/>
  <circle cx="24.6603" cy="11" r="1.2" fill="#FAF9F6"/>
  <circle cx="24.6603" cy="21" r="1.2" fill="#FAF9F6"/>
  <circle cx="16" cy="26" r="1.2" fill="#FAF9F6"/>
  <circle cx="7.33975" cy="21" r="1.2" fill="#FAF9F6"/>
  <circle cx="7.33975" cy="11" r="1.2" fill="#FAF9F6"/>
</svg>
"""
    with open(os.path.join(public_dir, "favicon.svg"), "w") as f:
        f.write(svg_content)
    print("Generated new favicon.svg")

    if not os.path.exists(template_path):
        print(f"Error: Template image not found at {template_path}")
        return

    # Open the template image generated by the AI
    img = Image.open(template_path)

    # 2. Save apple-touch-icon.png (180x180)
    apple_icon = img.resize((180, 180), Image.Resampling.LANCZOS)
    apple_icon.save(os.path.join(public_dir, "apple-touch-icon.png"), "PNG")
    print("Generated new apple-touch-icon.png")

    # 3. Save favicon.ico (multi-resolution 16x16, 32x32, 48x48)
    sizes = [16, 32, 48]
    images = [img.resize((sz, sz), Image.Resampling.LANCZOS) for sz in sizes]
    images[0].save(
        os.path.join(public_dir, "favicon.ico"),
        format="ICO",
        sizes=[(sz, sz) for sz in sizes],
        append_images=images[1:]
    )
    print("Generated new favicon.ico")

if __name__ == "__main__":
    generate_favicons()
